
services:
  collector:
    image: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest
    container_name: dynatrace-otel-collector-test
    command: ["--config", "/collector.yaml"]
    volumes:
      - ./config/collector-config.yaml:/collector.yaml:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
    network_mode: host
    pid: host
    privileged: true
    restart: unless-stopped