receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: "${env:DT_ENDPOINT}"
    headers:
      Authorization: "Api-Token ${env:API_TOKEN}"

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health"
    response_body:
      healthy: "Collector is healthy"
      unhealthy: "Collector is unhealthy"
  zpages:
    endpoint: "0.0.0.0:55679"

service:
  extensions: [health_check, zpages]
  telemetry:
    metrics:
      level: normal  # Enable internal telemetry for collector monitoring
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
    logs:
      level: info   # Enable internal logging
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [debug, otlphttp]