receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:

processors:
  resourcedetection:
    detectors: [env, system, dynatrace]
    timeout: 5s
    override: true
  cumulativetodelta:
    # Required: Converts cumulative metrics to delta temporality for Dynatrace
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: "${env:DT_ENDPOINT}"
    headers:
      Authorization: "Api-Token ${env:API_TOKEN}"
    timeout: 30s
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 1000

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"
    path: "/health"
    response_body:
      healthy: "Collector is healthy"
      unhealthy: "Collector is unhealthy"
  zpages:
    endpoint: "0.0.0.0:55679"

service:
  extensions: [health_check, zpages]
  telemetry:
    metrics:
      level: detailed  # Enhanced telemetry for comprehensive monitoring
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888
    logs:
      level: info   # Enable internal logging
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, cumulativetodelta, batch]
      exporters: [debug, otlphttp]