receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed

service:
  telemetry:
    metrics:
      level: none
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [batch]
      exporters: [debug]