# Configuration to test internal telemetry without hostmetrics
# This isolates internal telemetry from host metrics collection issues

receivers:
  # Using a simple receiver that doesn't require host access
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 500

service:
  telemetry:
    metrics:
      level: normal  # Try normal level
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]