version: '3.8'

services:
  diagnostics:
    build:
      context: .
      dockerfile: Dockerfile.diagnostics
    container_name: otel-diagnostics
    network_mode: bridge
    depends_on:
      - collector
    command: ["--continuous", "--interval", "60"]
    
  # Include collector service for standalone diagnostics testing
  collector:
    image: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector:latest
    container_name: dynatrace-otel-collector-diag
    command: ["--config", "/collector.yaml"]
    volumes:
      - ../config/collector-config.yaml:/collector.yaml:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
    environment:
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - HOST_ETC=/host/etc
      - DT_ENDPOINT=${DT_ENDPOINT}
      - API_TOKEN=${API_TOKEN}
    ports:
      - "8888:8888"   # Internal telemetry metrics endpoint
      - "13133:13133" # Health check endpoint
      - "55679:55679" # zPages diagnostic endpoint
    restart: unless-stopped